# Generated by Django 5.1.1 on 2024-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bloging", "0003_post_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="Thor-slugs", unique=True),
            preserve_default=False,
        ),
    ]
